surf = surface_create(window_get_width(), window_get_height());
sprite = noone;
surface_set_target(surf);
draw_surface(application_surface, 0, 0);
surface_reset_target();
instance_deactivate_all(1);
instance_activate_object(obj_menu_item);
physics_pause_enable(1);
c_x = surface_get_width(surf) / 2;
c_y = surface_get_height(surf) / 2;